import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";  // <--- THIS IS THE KEY LINE

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SLNS Billing Demo",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <script src="https://cdn.tailwindcss.com"></script>
      <script>
        {`
            tailwind.config = {
              theme: {
                extend: {
                  colors: {
                    slnsBlue: "#0B2447",
                    slnsGold: "#EAA300",
                    slnsLight: "#F0F4F8",
                  }
                }
              }
            }
          `}
      </script>
    </html>
  );
}